require('config.colorscheme')
require('config.completion')
require('config.fugitive')
require('config.lualine')
require('config.treesitter')
require('config.devicons')
require('config.telescope')
require('config.bufferline')
