project:
  type: website

profile:
  default: dev

execute:
  freeze: auto
  cache: true

theme: sandstone
engine: knitr
toc: true
number-sections: true
fig-dpi: 300
bibliography: references.bib
citeproc: true
link-citations: true
code-fold: true
code-overflow: wrap
highlight-style: gruvbox
