---
format:
    html:
        useMath: true
        standalone: true
        embed-resources: true
        self-contained: true
        self-contained-math: true
    # pdf:
    #     documentclass: article
    #     toc: false
    #     number-sections: true
    #     colorlinks: true
    #     #cite-method: biblatex
    #     header-includes:
    #       - |
    #         ```{=latex}
    #         \usepackage{fvextra}
    #         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
    #           breaksymbolleft={},
    #           showspaces = false,
    #           showtabs = false,
    #           breaklines,
    #           commandchars=\\\{\}
    #         }
    #         ```
    # gfm:
    #     output-file: "README"
    #     output-ext:  "md"
    #     fig-dpi: 300
title: "{{_cursor_}}"
author: "{{_author_}}"
#bibliography: cite.bib
citeproc: true
code-fold: true
fig-dpi: 300
engine: knitr
highlight-style: gruvbox
cache: false
code-overflow: wrap
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
#| label: imports-and-functions-r
#| code-summary: "Imports and Functions - R"
#| output: false

library(tidyverse)
library(reticulate)
library(ggthemes)
library(ggpubr)
library(kableExtra)
#library(EnvStats)
```

```{python}
#| label: imports-and-functions-python
#| code-summary: "Imports and Functions - Python"
#| output: false

import pysam
import pandas as pd
import matplotlib.pyplot as plt
import os
import json
from IPython.core.display import Markdown
from tabulate import tabulate
#import pybedtools
```
