vim.cmd("setlocal wrap")
vim.cmd("setlocal spell")
vim.cmd("setlocal linebreak")

vim.keymap.set("n", "<C-n>", "<cmd>MoltenNext<CR>", { desc = "Move to next cell", silent = true })
vim.keymap.set("n", "<C-p>", "<cmd>MoltenPrev<CR>", { desc = "Move to next cell", silent = true })

local runner = require("quarto.runner")
vim.keymap.set("n", "<C-s>", runner.run_cell, { desc = "run cell", silent = true })
vim.keymap.set("n", "<localleader>aa", runner.run_above, { desc = "run cell and above", silent = true })
vim.keymap.set("n", "<localleader>AA", runner.run_all, { desc = "run all cells", silent = true })
-- vim.keymap.set("n", "<localleader>rl", runner.run_line, { desc = "run line", silent = true })
vim.keymap.set("v", "<C-s>", runner.run_range, { desc = "run visual range", silent = true })
-- vim.keymap.set("n", "<localleader>RA", function()
-- 	runner.run_all(true)
-- end, { desc = "run all cells of all languages", silent = true })
